### ISSUE TITLE
Reference to non existing dist/admin.js file is resulting in error

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-multibranded-site#26]
class-admin.php has reference to ../dist/admin.js, which doesn't exist in codebase, resulting in error while accessing plugin settings page. It seems dist folder is missing from release archive.

![Screenshot](https://github.com/Automattic/newspack-multibranded-site/assets/7325107/b95f99e7-735f-43c4-8398-dff8db2c4eb1)

**Comment by claudiulodro** [comment]
Thanks for flagging the problem, Yogesh! Sorry on the delay, I've replaced the v1.0.0 zip with one that has all the necessary files: https://github.com/Automattic/newspack-multibranded-site/releases/tag/v1.0.0

**Comment by yogeshbeniwal** [comment]
Thanks @claudiulodro, it occurs again for [v1.0.1](https://github.com/Automattic/newspack-multibranded-site/releases/tag/v1.0.1), dist folder is being excluded somewhere in release pipeline.
